---
# playbook/nagios-server.yml

- hosts: monitor
  remote_user: vagrant
  become: yes

  roles:
    - nagios-server
    - nagios

- hosts: all
  remote_user: vagrant
  become: yes

  roles:
    - nagios
