---

- name:  mongodb | install MongoDB repository
  yum_repository:
    name: "mongo-org-3.6"
    description: "MongoDB Repository"
    baseurl: "{{ mongodb_baseurl }}"
    gpgcheck: yes
    gpgkey: "https://www.mongodb.org/static/pgp/server-3.6.asc"
    enabled: yes
  tags: mongodb

- name: mongodb | install MongoDB server
  package:
    name: "mongodb-org-{{ mongodb_version }}"
    state: present
  tags: mongodb

- name: mongodb | enable and start MongoDB
  service:
    name: mongod
    state: started
    enabled: yes
  tags: mongodb
