---


- name: restart mongodb
  service:
    name: mongodb
    state: restarted
    enabled: yes
  tags: mongodb

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
  tags: nginx

- name: alerta daemon-reload
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: alerta-app
  tags: alerta
